"use strict";
const TZ="America/Los_Angeles", APP_VERSION="SI-3.0.0", STALE_MIN=180, EVENT_SIGNAL=18, STRONG_SIGNAL=17;
const Z=[
 {name:"Gaviota",lat:34.48,lon:-120.23,regime:"western",targetDir:345,obsRadius:32,poly:[[34.39,-120.38],[34.39,-120.15],[34.58,-120.15],[34.60,-120.38]]},
 {name:"Refugio",lat:34.49,lon:-120.07,regime:"western",targetDir:355,obsRadius:28,poly:[[34.39,-120.15],[34.40,-119.96],[34.57,-119.96],[34.58,-120.15]]},
 {name:"Goleta",lat:34.45,lon:-119.83,regime:"hybrid",targetDir:5,obsRadius:24,poly:[[34.38,-119.96],[34.38,-119.76],[34.49,-119.76],[34.50,-119.96]]},
 {name:"San Marcos Pass",lat:34.51,lon:-119.80,regime:"hybrid",targetDir:10,obsRadius:22,poly:[[34.49,-119.96],[34.49,-119.74],[34.64,-119.72],[34.57,-119.96]]},
 {name:"Mission Canyon",lat:34.47,lon:-119.71,regime:"eastern",targetDir:15,obsRadius:20,poly:[[34.39,-119.76],[34.39,-119.67],[34.56,-119.67],[34.58,-119.74],[34.49,-119.76]]},
 {name:"Montecito",lat:34.45,lon:-119.63,regime:"eastern",targetDir:20,obsRadius:18,poly:[[34.39,-119.67],[34.39,-119.59],[34.54,-119.59],[34.56,-119.67]]},
 {name:"Toro Canyon",lat:34.44,lon:-119.57,regime:"eastern",targetDir:20,obsRadius:18,poly:[[34.38,-119.59],[34.38,-119.54],[34.52,-119.54],[34.54,-119.59]]},
 {name:"Carpinteria",lat:34.42,lon:-119.52,regime:"eastern",targetDir:25,obsRadius:20,poly:[[34.36,-119.54],[34.36,-119.43],[34.49,-119.43],[34.52,-119.54]]}
];
const FALLBACK_STATIONS=[
 {id:"GVTC1",name:"Gaviota RAWS",lat:34.4883,lon:-120.2358,type:"RAWS",role:"Front country"},
 {id:"RHWC1",name:"Refugio Hills RAWS",lat:34.5166,lon:-120.0753,type:"RAWS",role:"Front country"},
 {id:"MPWC1",name:"San Marcos Pass RAWS",lat:34.4913,lon:-119.7963,type:"RAWS",role:"Ridge"},
 {id:"SBVC1",name:"Santa Barbara Botanic Garden RAWS",lat:34.4558,lon:-119.7056,type:"RAWS",role:"Front country"},
 {id:"CXPC1",name:"Carpinteria RAWS",lat:34.4444,lon:-119.5131,type:"RAWS",role:"Front country"},
 {id:"SYAC1",name:"Santa Ynez Valley Fire Station",lat:34.6063,lon:-120.0700,type:"RAWS",role:"Santa Ynez precursor"},
 {id:"BMFC1",name:"Burton Mesa Fire Station",lat:34.6975,lon:-120.4500,type:"RAWS",role:"North County precursor"},
 {id:"TSQC1",name:"Tepusquet RAWS",lat:34.9198,lon:-120.181,type:"RAWS",role:"North County precursor"},
 {id:"CUVC1",name:"Cuyama Valley RAWS",lat:34.9653,lon:-119.8803,type:"RAWS",role:"Cuyama precursor"},
 {id:"LPOC1",name:"Los Prietos RAWS",lat:34.5444,lon:-119.7914,type:"RAWS",role:"Upstream ridge"},
 {id:"FGMC1",name:"Figueroa Mountain RAWS",lat:34.7344,lon:-120.0067,type:"RAWS",role:"Upstream ridge"},
 {id:"MTIC1",name:"Montecito Hills RAWS",lat:34.461,lon:-119.649,type:"RAWS",role:"Front country"},
 {id:"MOIC1",name:"Montecito RAWS #2",lat:34.4450,lon:-119.62583,type:"RAWS",role:"Front country"},
 {id:"VDBC1",name:"Vandenberg RAWS",lat:34.7586,lon:-120.4861,type:"RAWS",role:"Northwest precursor"},
 {id:"SRIC1",name:"Santa Rosa Island RAWS",lat:33.98,lon:-120.08,type:"RAWS",role:"Marine reference"}
];
const KNOWN_RAWS=new Set(FALLBACK_STATIONS.map(s=>s.id));
const HV=["temperature_2m","relative_humidity_2m","pressure_msl","cloud_cover_low","wind_speed_10m","wind_direction_10m","wind_gusts_10m","boundary_layer_height","lifted_index","shortwave_radiation","relative_humidity_925hPa","wind_speed_925hPa","wind_direction_925hPa","temperature_925hPa","wind_speed_850hPa","wind_direction_850hPa","temperature_850hPa","wind_speed_700hPa","wind_direction_700hPa","temperature_700hPa","wind_speed_500hPa","wind_direction_500hPa","vertical_velocity_850hPa"];
let map=null,zoneMarkers={},zoneLabels={},stationMarkers=[],R=[],ST=[],CATALOG=[],PS=null,OBS_PRESS=null,COAST=null,health={},focus=null,NWS_CACHE={},lastRefresh=null,CAL=null,EVENTS=null;
const $=x=>document.getElementById(x), clamp=(x,a,b)=>Math.max(a,Math.min(b,x)), sig=x=>1/(1+Math.exp(-x)), rad=x=>x*Math.PI/180;
function finite(x){return Number.isFinite(Number(x))}function num(x){let n=Number(x);return Number.isFinite(n)?n:null}
function signedComponent(dir,target){if(!finite(dir))return 0;return Math.cos(rad((((Number(dir)-target)+540)%360)-180))}
function dirComponent(dir,target){return Math.max(0,signedComponent(dir,target))}
function cat(p){return p>=60?"EXTREME":p>=35?"HIGH":p>=EVENT_SIGNAL?"ELEVATED":"LOW"}function col(p){return p>=60?"#eb5757":p>=35?"#f2994a":p>=EVENT_SIGNAL?"#f2c94c":"#35c98a"}
function compass(d){if(!finite(d))return"—";let a=["N","NNE","NE","ENE","E","ESE","SE","SSE","S","SSW","SW","WSW","W","WNW","NW","NNW"];return a[Math.round(((Number(d)%360)+360)%360/22.5)%16]}
function ft(t){if(!t)return"—";return new Date(t).toLocaleString("en-US",{weekday:"short",hour:"numeric",minute:"2-digit",timeZone:TZ})}
function ageMinutes(t){if(!t)return Infinity;let d=new Date(t);return Number.isFinite(d.getTime())?Math.max(0,(Date.now()-d.getTime())/60000):Infinity}
function age(t){let m=ageMinutes(t);if(!Number.isFinite(m))return"—";return m<60?Math.round(m)+"m":(m<1440?Math.round(m/60)+"h":Math.round(m/1440)+"d")}
function distMi(a,b){let lat=(a.lat+b.lat)/2*rad(1),dx=(a.lon-b.lon)*69.172*Math.cos(lat),dy=(a.lat-b.lat)*69.0;return Math.hypot(dx,dy)}
function fmtSigned(x,d=1){return finite(x)?`${Number(x)>=0?"+":""}${Number(x).toFixed(d)}`:"—"}
function statusClass(s){return s==="Fresh"?"fresh":s==="Stale"?"stale":"offline"}
function sourceHealth(name,value,level="info"){health[name]={value,level,time:new Date().toISOString()};if(typeof renderHealth==="function")renderHealth()}
async function json(url,opts={},attempts=2){let last;for(let a=0;a<attempts;a++){let ctl=new AbortController(),to=setTimeout(()=>ctl.abort(),15000);try{let r=await fetch(url,{...opts,signal:ctl.signal,cache:"no-store"});clearTimeout(to);if(!r.ok){let text="";try{text=(await r.text()).slice(0,160)}catch(_e){}throw Error(`${r.status}${text?": "+text:""}`)}return await r.json()}catch(e){clearTimeout(to);last=e;if(a+1<attempts)await new Promise(res=>setTimeout(res,350*(a+1)))}}throw last}
function choose(obj,patterns){if(!obj)return null;for(let [k,v] of Object.entries(obj)){if(v==null||v==="")continue;if(patterns.some(p=>p.test(k))){let n=Number(v);if(Number.isFinite(n))return{k,v:n}}}return null}
function chooseTime(obj){if(!obj)return null;for(let k of ["utc_valid","valid","valid_time","observation_time","timestamp","time"]){if(obj[k])return obj[k]}return null}
function roleFor(meta){if(meta.role)return meta.role;let id=String(meta.id||""),lat=Number(meta.lat),lon=Number(meta.lon);if(["CUVC1"].includes(id)||(lat>34.82&&lon>-120.05&&lon<-119.35))return"Cuyama precursor";if(["SYAC1","FGMC1","LPOC1"].includes(id)||(lat>34.54&&lat<34.82&&lon>-120.20&&lon<-119.55))return"Santa Ynez / ridge precursor";if(lat>=35.0&&lon>-120.25&&lon<-118.55)return"Southern Kern precursor";if(["VDBC1","TSQC1","BMFC1"].includes(id)||lat>34.68)return"North County precursor";if(lat<34.2)return"Marine reference";return"Front country"}
function isRawsMeta(s){return KNOWN_RAWS.has(s.id)||/\bRAWS\b|FIRE WEATHER/i.test(s.name||"")}
async function currentStation(meta){try{let j=await json(`https://mesonet.agron.iastate.edu/json/current.py?station=${encodeURIComponent(meta.id)}&network=CA_DCP`,{},2);let o=j.last_ob||j.data||j.current||j.observation||{};if(Array.isArray(o))o=o[0]||{};
 let wsp=choose(o,[/^windspeed\[kt\]$/i,/wind.*speed.*\[kt\]/i]),gust=choose(o,[/^gust\[kt\]$/i,/windgust\[kt\]/i,/gust.*\[kt\]/i]),dir=choose(o,[/winddirection\[deg\]/i,/wind.*dir/i,/^UD/i]),rh=choose(o,[/relativehumidity/i,/relh/i,/^XR/i]),temp=choose(o,[/airtemp\[F\]/i,/air.*temp/i,/^TA/i]),fm=choose(o,[/fuel.*moist/i,/moist.*fuel/i,/^MM/i]);
 if(!wsp)wsp=choose(o,[/^US/i,/wind.*speed/i]);if(!gust)gust=choose(o,[/^UP/i,/peak.*wind/i,/gust/i]);let wind=wsp?wsp.v:null,g=wind;if(wsp&&/\[kt\]|knot/i.test(wsp.k))g*=1.15078;let gg=gust?gust.v:null;if(gust&&/\[kt\]|knot/i.test(gust.k))gg*=1.15078;
 let t=chooseTime(o),mins=ageMinutes(t),status=Number.isFinite(mins)?(mins<=STALE_MIN?"Fresh":"Stale"):"Offline",detectedRaws=isRawsMeta(meta)||(!!fm&&finite(g)&&finite(dir?.v));return{...meta,role:roleFor(meta),type:detectedRaws?"RAWS":(meta.type||"DCP"),wind:g,gust:gg,dir:dir?dir.v:null,rh:rh?rh.v:null,temp:temp?temp.v:null,fuelMoist:fm?fm.v:null,time:t,status,fresh:status==="Fresh"&&finite(g)&&finite(dir?.v)}
 }catch(e){return{...meta,role:roleFor(meta),type:isRawsMeta(meta)?"RAWS":(meta.type||"DCP"),wind:null,gust:null,dir:null,rh:null,temp:null,fuelMoist:null,time:null,status:"Offline",fresh:false,error:String(e.message||e)}}}
async function discoverStations(){let cached=null;try{cached=JSON.parse(localStorage.getItem("sundowner:stations:v3"))}catch(_e){}let items=[];try{let gj=await json("https://mesonet.agron.iastate.edu/geojson/network.py?network=CA_DCP",{},2);for(let f of gj.features||[]){let p=f.properties||{},c=f.geometry?.coordinates||[],id=p.sid||p.id||p.station||p.stid,name=p.sname||p.name||p.station_name||id,county=String(p.county||p.county_name||"").trim().toLowerCase(),lon=num(c[0]),lat=num(c[1]);if(!id||!finite(lat)||!finite(lon))continue;let sb=county.includes("santa barbara")||(lat>=34.30&&lat<=35.15&&lon>=-120.75&&lon<=-119.25),up=(lat>=34.55&&lat<=35.65&&lon>=-120.55&&lon<=-118.55);if(sb||up)items.push({id:String(id),name:String(name||id),lat:Number(lat),lon:Number(lon),type:/RAWS/i.test(String(name))?"RAWS":"DCP",role:roleFor({id,lat,lon})})}if(!items.length)throw Error("No stations in discovery envelope");try{localStorage.setItem("sundowner:stations:v3",JSON.stringify({saved:Date.now(),items}))}catch(_e){}sourceHealth("Station catalog",`${items.length} county/upstream stations discovered`,"good")}catch(e){items=cached?.items||[];sourceHealth("Station catalog",items.length?`Discovery failed; ${items.length} cached stations retained`:`Discovery failed; verified fallback stations only`,items.length?"warn":"err")}
 let m=new Map(items.map(s=>[s.id,{...s}]));for(let s of FALLBACK_STATIONS){if(!m.has(s.id))m.set(s.id,{...s,fallback:true});else m.set(s.id,{...m.get(s.id),...s,role:s.role})}return [...m.values()].filter(s=>s.lat>=33.8&&s.lat<=35.65&&s.lon>=-120.75&&s.lon<=-118.55).sort((a,b)=>(a.role||"").localeCompare(b.role||"")||a.name.localeCompare(b.name))}
async function loadStations(){CATALOG=await discoverStations();let out=new Array(CATALOG.length),i=0,workers=Math.min(14,CATALOG.length);async function worker(){while(i<CATALOG.length){let idx=i++;out[idx]=await currentStation(CATALOG[idx])}}await Promise.all(Array.from({length:workers},worker));ST=out;let fresh=ST.filter(s=>s.fresh).length,raws=ST.filter(s=>s.type==="RAWS").length,up=ST.filter(s=>s.fresh&&/precursor|upstream/i.test(s.role||"")).length;sourceHealth("Live observations",`${fresh}/${ST.length} fresh • ${raws} RAWS • ${up} fresh upstream`,fresh?"good":"warn");return ST}
function freshestStations(){return ST.filter(s=>s.fresh&&ageMinutes(s.time)<=STALE_MIN)}
function stationInfluence(z,s){let d=distMi(z,s),distance=Math.exp(-Math.pow(d/Math.max(z.obsRadius,10),1.35)),freshness=Math.exp(-ageMinutes(s.time)/125),raws=s.type==="RAWS"?1.22:1,quality=finite(s.gust)?1.05:1;return distance*freshness*raws*quality}
function obsSignal(z){let sum=0,w=0,n=0;for(let s of freshestStations().filter(s=>!/precursor|upstream/i.test(s.role||""))){let ws=Math.max(Number(s.gust)||0,Number(s.wind)||0);if(!ws||!finite(s.dir))continue;let wt=stationInfluence(z,s);if(wt<.015)continue;let component=ws*dirComponent(s.dir,z.targetDir),v=clamp((component-9)/31,0,1);sum+=v*wt;w+=wt;n++}return{signal:w?clamp(sum/w,0,1):0,count:n,weight:w}}
function obsGustCorrection(z){let vals=[];for(let s of freshestStations().filter(s=>!/precursor|upstream/i.test(s.role||""))){let ws=Math.max(Number(s.gust)||0,Number(s.wind)||0);if(!ws)continue;let d=distMi(z,s);if(d>Math.max(35,z.obsRadius*1.6))continue;let wt=stationInfluence(z,s);vals.push({v:ws,w:wt})}let w=vals.reduce((a,x)=>a+x.w,0);return{gust:w?vals.reduce((a,x)=>a+x.v*x.w,0)/w:null,weight:w,count:vals.length}}
function upstreamSignal(z){let ss=freshestStations().filter(s=>/precursor|upstream/i.test(s.role||"")),sum=0,w=0,n=0,detail=[];for(let s of ss){let ws=Math.max(Number(s.gust)||0,Number(s.wind)||0),north=dirComponent(s.dir,z.regime==="western"?345:5),wind=clamp((ws*north-8)/28,0,1),dry=finite(s.rh)?clamp((40-Number(s.rh))/30,0,1):.35,wt=Math.exp(-ageMinutes(s.time)/150)*(s.type==="RAWS"?1.2:1),v=.68*wind+.32*dry;sum+=v*wt;w+=wt;n++;detail.push({id:s.id,name:s.name,role:s.role,v,wind:ws,dir:s.dir,rh:s.rh})}return{signal:w?clamp(sum/w,0,1):0,count:n,detail:detail.sort((a,b)=>b.v-a.v).slice(0,4)}}
function fuelSignal(){let vals=freshestStations().map(s=>num(s.fuelMoist)).filter(x=>finite(x)&&x>0&&x<80).sort((a,b)=>a-b);if(!vals.length)return{value:null,signal:.35,n:0};let m=vals[Math.floor(vals.length/2)];return{value:m,signal:clamp((16-m)/11,0,1),n:vals.length}}
