"use strict";
const DEFAULT_CAL={version:"SI-3.0-physical",event:{intercept:0,slope:1},strong:{intercept:0,slope:1},zone_bias_mph:{},notes:"Physical fallback"};
async function loadArtifacts(){try{CAL=await json(`./calibration.json?v=${Date.now()}`,{},1);sourceHealth("Historical calibration",`${CAL.version||"calibration"} loaded`,"good")}catch(e){CAL=DEFAULT_CAL;sourceHealth("Historical calibration","Central artifact unavailable; physical fallback active","warn")}try{EVENTS=await json(`./data/known-sundowner-events.json?v=${Date.now()}`,{},1);let a=EVENTS.events||[],fire=a.filter(x=>x.fire_associated).length;sourceHealth("Historical event catalog",`${a.length} documented events • ${a.length-fire} non-fire • ${fire} fire-associated`,"good")}catch(e){EVENTS={events:[]};sourceHealth("Historical event catalog","Unavailable","warn")}}
async function model(lat,lon,which="gfs_seamless",vars=HV){let q=new URLSearchParams({latitude:lat,longitude:lon,hourly:vars.join(","),wind_speed_unit:"mph",temperature_unit:"fahrenheit",timezone:TZ,forecast_hours:"48",models:which});return json("https://api.open-meteo.com/v1/forecast?"+q,{},2)}
function mergeHourly(base,overlay){if(!base?.hourly)return overlay;if(!overlay?.hourly)return base;let bt=base.hourly.time||[],ot=overlay.hourly.time||[],oi=new Map(ot.map((t,i)=>[t,i])),out={...base,hourly:{...base.hourly}};for(let [k,a] of Object.entries(base.hourly)){if(k==="time"||!Array.isArray(a))continue;let oa=overlay.hourly[k];if(!Array.isArray(oa))continue;out.hourly[k]=bt.map((t,i)=>{let j=oi.get(t),v=j==null?null:oa[j];return v==null?a[i]:v})}for(let [k,oa] of Object.entries(overlay.hourly)){if(k==="time"||out.hourly[k]||!Array.isArray(oa))continue;out.hourly[k]=bt.map(t=>{let j=oi.get(t);return j==null?null:oa[j]})}return out}
async function zoneGuidance(z){let seamless=null,hr=null,nbm=null;try{seamless=await model(z.lat,z.lon,"gfs_seamless");sourceHealth("GFS seamless","48-hour NOAA GFS fallback/extension available","good")}catch(e){sourceHealth("GFS seamless",`Unavailable: ${e.message}`,"warn")}
 try{hr=await model(z.lat,z.lon,"gfs_hrrr");sourceHealth("HRRR","Explicit NOAA HRRR 3-km guidance available","good")}catch(e){sourceHealth("HRRR",`Unavailable: ${e.message}`,"warn")}if(!hr&&!seamless)throw Error("No HRRR or GFS forecast guidance");let hrrr=mergeHourly(seamless||hr,hr);
 try{nbm=await model(z.lat,z.lon,"ncep_nbm_conus",["temperature_2m","relative_humidity_2m","wind_speed_10m","wind_direction_10m","wind_gusts_10m"]);sourceHealth("NBM","NOAA NBM surface blend available","good")}catch(e){sourceHealth("NBM",`Unavailable: ${e.message}`,"warn")}
 return{hrrr,nbm}}
async function coastalGuidance(){try{let x=await model(34.455,-120.47,"gfs_hrrr",["wind_speed_10m","wind_direction_10m","wind_gusts_10m"]);sourceHealth("Point Conception coastal jet","HRRR coastal reference loaded","good");return x.hourly}catch(e){try{let x=await model(34.455,-120.47,"gfs_seamless",["wind_speed_10m","wind_direction_10m","wind_gusts_10m"]);sourceHealth("Point Conception coastal jet","GFS fallback reference loaded","warn");return x.hourly}catch(e2){sourceHealth("Point Conception coastal jet","Unavailable","warn");return null}}}
const PRESSURE_POINTS={sba:{id:"KSBA",lat:34.4262,lon:-119.8404},bfl:{id:"KBFL",lat:35.4336,lon:-119.0568},smx:{id:"KSMX",lat:34.8993,lon:-120.4576},iza:{id:"KIZA",lat:34.6068,lon:-120.0756},vbg:{id:"KVBG",lat:34.7373,lon:-120.5843},lpc:{id:"KLPC",lat:34.6656,lon:-120.4675}};
async function pressureModel(){let out={};for(let [k,p] of Object.entries(PRESSURE_POINTS)){try{out[k]=await model(p.lat,p.lon,"gfs_seamless",["pressure_msl"])}catch(e){out[k]=null}}let base=out.sba;if(!base)throw Error("SBA pressure forecast unavailable");let t=base.hourly.time,series=(k,i)=>out[k]?.hourly?.pressure_msl?.[i],diff=(k,i)=>finite(series("sba",i))&&finite(series(k,i))?series("sba",i)-series(k,i):null;let fields={time:t};for(let k of ["bfl","smx","iza","vbg","lpc"])fields[k]=t.map((_,i)=>diff(k,i));sourceHealth("Forecast pressure field","SBA relative to BFL/SMX/IZA/VBG/LPC loaded","good");return fields}
function pressureFromObservation(p){let pa=num(p?.seaLevelPressure?.value??p?.barometricPressure?.value);return finite(pa)?pa/100:null}
async function airportHistory(id){let j=await json(`https://api.weather.gov/stations/${id}/observations?limit=8`,{headers:{Accept:"application/geo+json"}},2),a=(j.features||[]).map(f=>({hpa:pressureFromObservation(f.properties),time:f.properties?.timestamp})).filter(x=>finite(x.hpa)&&x.time);if(!a.length)throw Error("pressure missing");a.sort((x,y)=>new Date(y.time)-new Date(x.time));let latest=a[0],target=new Date(latest.time).getTime()-3*3600000,prior=a.reduce((best,x)=>Math.abs(new Date(x.time).getTime()-target)<Math.abs(new Date(best.time).getTime()-target)?x:best,a[a.length-1]);return{hpa:latest.hpa,time:latest.time,tendency3h:latest.hpa-prior.hpa}}
async function observedPressure(){let got={};await Promise.all(Object.entries(PRESSURE_POINTS).map(async([k,p])=>{try{got[k]=await airportHistory(p.id)}catch(e){got[k]=null}}));if(!got.sba){sourceHealth("Observed pressure field","SBA observation unavailable","warn");return null}let o={time:got.sba.time,stations:got,grad:{},trend:{}};for(let k of ["bfl","smx","iza","vbg","lpc"]){if(got[k]){o.grad[k]=got.sba.hpa-got[k].hpa;o.trend[k]=got.sba.tendency3h-got[k].tendency3h}}let txt=Object.entries(o.grad).map(([k,v])=>`SBA–${k.toUpperCase()} ${fmtSigned(v)}`).join(" • ");sourceHealth("Observed pressure field",txt||"Partial field unavailable",Object.keys(o.grad).length>=3?"good":"warn");return o}
function pressureAt(t){let i=PS?.time?.indexOf(t)??-1;if(i<0)i=0;let out={};for(let k of ["bfl","smx","iza","vbg","lpc"]){let f=PS?.[k]?.[i],v=finite(f)?Number(f):null;if(OBS_PRESS?.grad?.[k]!=null){let lead=Math.max(0,(new Date(t)-Date.now())/3600000),blend=clamp(1-lead/6,0,1);v=v==null?OBS_PRESS.grad[k]:v*(1-blend)+OBS_PRESS.grad[k]*blend}out[k]=v;out[`${k}Trend`]=OBS_PRESS?.trend?.[k]??null}return out}
function coastAt(t){if(!COAST?.time)return{signal:0,wind:null,dir:null};let i=COAST.time.indexOf(t);if(i<0)i=0;let wind=num(COAST.wind_gusts_10m?.[i]??COAST.wind_speed_10m?.[i]),dir=num(COAST.wind_direction_10m?.[i]),signal=finite(wind)&&finite(dir)?clamp((wind*dirComponent(dir,325)-12)/30,0,1):0;return{signal,wind,dir}}
function localPressureSupport(P,z){let west=[P.smx,P.vbg,P.lpc,P.iza].filter(finite),east=[P.bfl,P.iza].filter(finite),hy=[P.bfl,P.smx,P.iza].filter(finite),avg=a=>a.length?a.reduce((s,x)=>s+x,0)/a.length:0,g=z.regime==="western"?avg(west):z.regime==="eastern"?avg(east):avg(hy),threshold=z.regime==="western"?-1.7:-1.2,scale=z.regime==="western"?.9:1.0,base=sig((-g+threshold)/scale);let trends=[P.bflTrend,P.smxTrend,P.izaTrend,P.vbgTrend,P.lpcTrend].filter(finite),trend=trends.length?avg(trends):0,trendBoost=clamp((-trend+.2)/1.6,0,1);return{signal:clamp(.82*base+.18*trendBoost,0,1),mean:g,trend}}
function vector(h,n,i,z){let t=h.time[i],P=pressureAt(t),pr=localPressureSupport(P,z),g=num(h.wind_gusts_10m?.[i])||0,ng=num(n?.wind_gusts_10m?.[i]),d=num(h.wind_direction_10m?.[i]),w925=num(h.wind_speed_925hPa?.[i])||0,d925=num(h.wind_direction_925hPa?.[i]),w8=num(h.wind_speed_850hPa?.[i])||0,d8=num(h.wind_direction_850hPa?.[i]),w7=num(h.wind_speed_700hPa?.[i])||0,d7=num(h.wind_direction_700hPa?.[i]),w5=num(h.wind_speed_500hPa?.[i])||0,d5=num(h.wind_direction_500hPa?.[i]),rh=num(h.relative_humidity_2m?.[i])??50,bl=num(h.boundary_layer_height?.[i])??1000,li=num(h.lifted_index?.[i])??0,sol=num(h.shortwave_radiation?.[i])??0,r925=num(h.relative_humidity_925hPa?.[i])??50,low=num(h.cloud_cover_low?.[i])??0,vv=num(h.vertical_velocity_850hPa?.[i])??0;
 let hour=parseInt(t.slice(11,13)),eve=(hour>=16||hour<=5)?1:0,r925w=clamp((w925*dirComponent(d925,z.targetDir)-10)/28,0,1),r8=clamp((w8*dirComponent(d8,z.targetDir)-12)/30,0,1),r7=clamp((w7*dirComponent(d7,z.targetDir)-16)/36,0,1),surf=clamp((g*dirComponent(d,z.targetDir)-12)/34,0,1),dry=clamp((36-rh)/29,0,1),marine=clamp((r925-48)/42,0,1)*clamp((1450-bl)/1100,0,1)*clamp((low+15)/100,0,1),stab=clamp((li+2)/8,0,1),tw=eve?1:clamp((350-sol)/350,0,1),obs=obsSignal(z),up=upstreamSignal(z),og=obsGustCorrection(z),downslope=clamp((-vv+.4)/1.2,0,1),c8=signedComponent(d8,z.targetDir),c7=signedComponent(d7,z.targetDir),c5=signedComponent(d5,z.targetDir),shear=clamp(Math.abs(w8*c8-w7*c7)/35,0,1),critical=clamp((c8-Math.min(c7,c5)+.05)/1.15,0,1)*clamp((w8-15)/25,0,1),coast=coastAt(t),nbmG=finite(ng)?Number(ng):null,baseG=nbmG!=null?.58*nbmG+.42*g:g,obsBlend=og.gust!=null?clamp(og.weight/(og.weight+1.6),0,.42):0,bias=num(CAL?.zone_bias_mph?.[z.name])||0,localG=Math.max(0,baseG*(1-obsBlend)+(og.gust??baseG)*obsBlend+bias);
 return{press:pr.signal,pressureMean:pr.mean,pressureTrend:pr.trend,r925w,r8,r7,shear,critical,surf,dry,marine,stab,tw,eve,obs:obs.signal,obsN:obs.count,upstream:up.signal,upstreamN:up.count,upstreamDetail:up.detail,downslope,coastalJet:coast.signal,coastalWind:coast.wind,coastalDir:coast.dir,b:P.bfl,s:P.smx,iza:P.iza,vbg:P.vbg,lpc:P.lpc,g,d,w925,d925,w8,d8,w7,d7,w5,d5,rh,bl,time:t,solar:sol,nbmG,baseG,localG,ogN:og.count}}
function physicalLogit(v,z){let x=-4.25+1.72*v.press+1.18*v.r8+.42*v.r7+.34*v.r925w+.50*v.downslope+.55*v.surf+.44*v.dry+.30*v.stab+.32*v.critical+.18*v.shear+.48*(1-v.marine)+.38*v.tw+.18*v.eve+.68*v.upstream+.56*v.obs+.24*v.coastalJet;if(z.regime==="hybrid")x+=.08;if(z.regime==="western")x+=.10*v.coastalJet;return x}
function calibratedProbability(v,z){let raw=sig(physicalLogit(v,z)),c=CAL?.models?.[z.regime]?.event||CAL?.event;if(c&&finite(c.intercept)&&finite(c.slope)){let l=Math.log(clamp(raw,.001,.999)/(1-clamp(raw,.001,.999)));return sig(Number(c.intercept)+Number(c.slope)*l)}return raw}
function strongProbability(v,p,z){let westGrad=sig((-Number(v.s||0)-3.4)/.45),eastGrad=sig((-Number(v.b||0)-4.2)/.55),grad=z.regime==="western"?westGrad:z.regime==="eastern"?eastGrad:Math.max(westGrad,eastGrad),gust=sig((v.localG-35)/3.8),aloft=clamp(.56*v.r8+.24*v.r7+.20*v.critical,0,1),base=clamp((p-.12)/.72,0,1),raw=sig(-4.4+1.65*grad+1.50*gust+.92*aloft+.45*v.downslope+.40*v.upstream+.32*v.obs+.30*base),c=CAL?.models?.[z.regime]?.strong||CAL?.strong;if(c&&finite(c.intercept)&&finite(c.slope)){let l=Math.log(clamp(raw,.001,.999)/(1-clamp(raw,.001,.999)));return sig(Number(c.intercept)+Number(c.slope)*l)}return raw}
function score(h,n,i,z){let v=vector(h,n,i,z),p=calibratedProbability(v,z),strong=strongProbability(v,p,z),fuel=fuelSignal(),fresh=freshestStations(),sourceCount=3+(n?1:0)+(OBS_PRESS?1:0)+(COAST?1:0)+(CAL&&CAL!==DEFAULT_CAL?1:0),obsCov=clamp(v.obsN/5,0,1),upCov=clamp(v.upstreamN/4,0,1),conf=clamp(Math.round(38+sourceCount*5+obsCov*15+upCov*10),35,97),fire=sig(-3.35+1.65*strong+1.15*v.dry+.95*v.surf+.75*fuel.signal+.45*v.obs+.35*clamp((v.localG-25)/25,0,1));return{...v,p:Math.round(p*100),strong:Math.round(strong*100),fire:Math.round(fire*100),fuelMoist:fuel.value,conf,localG:v.localG}}
async function buildZone(z){let {hrrr,nbm}=await zoneGuidance(z),h=hrrr.hourly,n=nbm?.hourly||null,a=h.time.slice(0,48).map((_,i)=>score(h,n,i,z)),pk=a.reduce((x,y)=>!x||y.p>x.p?y:x,null),gpk=a.reduce((x,y)=>!x||y.localG>x.localG?y:x,null);return{...z,a,pk,gpk}}
