async function model(lat,lon,which="hrrr_conus",vars=HV){let q=new URLSearchParams({latitude:lat,longitude:lon,hourly:vars.join(","),wind_speed_unit:"mph",temperature_unit:"fahrenheit",timezone:TZ,forecast_hours:"48",models:which});return json("https://api.open-meteo.com/v1/gfs?"+q,{},2)}
async function zoneGuidance(z){let hrrr=null,nbm=null;try{hrrr=await model(z.lat,z.lon,"hrrr_conus");sourceHealth("HRRR",`Primary 3-km guidance available`,"good")}catch(e){sourceHealth("HRRR",`Explicit HRRR unavailable: ${e.message}`,"warn");try{hrrr=await model(z.lat,z.lon,"gfs_seamless");sourceHealth("HRRR fallback","GFS seamless fallback active","warn")}catch(e2){throw Error(`No forecast model: ${e2.message}`)}}
 try{nbm=await model(z.lat,z.lon,"nbm_conus",["temperature_2m","relative_humidity_2m","wind_speed_10m","wind_direction_10m","wind_gusts_10m"]);sourceHealth("NBM",`Surface blend available`,"good")}catch(e){sourceHealth("NBM",`Unavailable; HRRR-only localization`,"warn")}
 return{hrrr,nbm}}
async function pressureModel(){let pts={sba:[34.4262,-119.8404],bfl:[35.4336,-119.0568],smx:[34.8993,-120.4576]},out={};for(let [k,p] of Object.entries(pts)){try{out[k]=await model(p[0],p[1],"hrrr_conus",["pressure_msl"])}catch(e){out[k]=await model(p[0],p[1],"gfs_seamless",["pressure_msl"])}}
 let t=out.sba.hourly.time,b=t.map((_,i)=>(out.sba.hourly.pressure_msl[i]??0)-(out.bfl.hourly.pressure_msl[i]??0)),s=t.map((_,i)=>(out.sba.hourly.pressure_msl[i]??0)-(out.smx.hourly.pressure_msl[i]??0));sourceHealth("Forecast pressure gradients","SBA–BFL and SBA–SMX loaded","good");return{time:t,b,s}}
async function airportPressure(id){let j=await json(`https://api.weather.gov/stations/${id}/observations/latest`,{headers:{Accept:"application/geo+json"}},2),p=j.properties||{},pa=num(p.seaLevelPressure?.value??p.barometricPressure?.value);if(!finite(pa))throw Error("pressure missing");return{hpa:pa/100,time:p.timestamp||null}}
async function observedPressure(){try{let [sba,bfl,smx]=await Promise.all([airportPressure("KSBA"),airportPressure("KBFL"),airportPressure("KSMX")]);let o={b:sba.hpa-bfl.hpa,s:sba.hpa-smx.hpa,time:[sba.time,bfl.time,smx.time]};sourceHealth("Observed pressure gradients",`SBA–BFL ${fmtSigned(o.b)} mb • SBA–SMX ${fmtSigned(o.s)} mb`,"good");return o}catch(e){sourceHealth("Observed pressure gradients",`Unavailable: ${e.message}`,"warn");return null}}
function pa(t){let i=PS?.time?.indexOf(t)??-1;if(i<0)i=0;let b=PS?.b?.[i]??0,s=PS?.s?.[i]??0;if(OBS_PRESS){let lead=Math.max(0,(new Date(t)-Date.now())/3600000),blend=clamp(1-lead/6,0,1);b=b*(1-blend)+OBS_PRESS.b*blend;s=s*(1-blend)+OBS_PRESS.s*blend}return{b,s}}
function vector(h,n,i,z){let P=pa(h.time[i]),g=h.wind_gusts_10m[i]||0,ng=n?.wind_gusts_10m?.[i],d=h.wind_direction_10m[i],w8=h.wind_speed_850hPa[i]||0,d8=h.wind_direction_850hPa[i],t8=h.temperature_850hPa?.[i],w7=h.wind_speed_700hPa[i]||0,d7=h.wind_direction_700hPa[i],rh=h.relative_humidity_2m[i]??50,bl=h.boundary_layer_height[i]??1000,li=h.lifted_index[i]??0,sol=h.shortwave_radiation[i]??0,r925=h.relative_humidity_925hPa[i]??50,low=h.cloud_cover_low[i]??0,vv=h.vertical_velocity_850hPa?.[i]??0;
 let hour=parseInt(h.time[i].slice(11,13)),eve=(hour>=16||hour<=5)?1:0;let westP=sig((-P.s-1.8)/.8),eastP=sig((-P.b-1.2)/1.0),press=z.regime==="western"?westP:z.regime==="eastern"?eastP:Math.max(westP,eastP);let r8=clamp((w8*dirComponent(d8,z.targetDir)-12)/30,0,1),r7=clamp((w7*dirComponent(d7,z.targetDir)-16)/36,0,1),surf=clamp((g*dirComponent(d,z.targetDir)-12)/34,0,1),dry=clamp((36-rh)/29,0,1),marine=clamp((r925-48)/42,0,1)*clamp((1450-bl)/1100,0,1)*clamp((low+15)/100,0,1),stab=clamp((li+2)/8,0,1),tw=eve?1:clamp((350-sol)/350,0,1),obs=obsSignal(z),og=obsGustCorrection(z);let downslope=clamp((-vv+.4)/1.2,0,1),nbmG=finite(ng)?Number(ng):null,baseG=nbmG!=null?.58*nbmG+.42*g:g,obsBlend=og.gust!=null?clamp(og.weight/(og.weight+1.6),0,.42):0,localG=baseG*(1-obsBlend)+(og.gust??baseG)*obsBlend;
 return{press,r8,r7,surf,dry,marine,stab,tw,eve,obs:obs.signal,obsN:obs.count,downslope,b:P.b,s:P.s,g,d,w8,d8,w7,d7,rh,bl,time:h.time[i],solar:sol,t8,nbmG,baseG,localG,ogN:og.count}}
function probability(v,z){let x=-4.05+1.9*v.press+1.32*v.r8+.48*v.r7+.52*v.downslope+.72*v.surf+.52*v.dry+.32*v.stab+.55*(1-v.marine)+.52*v.tw+.28*v.eve+.90*v.obs;if(z.regime==="hybrid")x+=.08;return sig(x)}
function strongProbability(v,p){let gustSig=clamp((v.localG-26)/22,0,1),x=-3.55+1.05*clamp((p-.12)/.75,0,1)+1.25*v.press+1.05*v.r8+.70*v.surf+.85*gustSig+.55*v.obs+.35*(1-v.marine);return sig(x)}
function score(h,n,i,z){let v=vector(h,n,i,z),p=probability(v,z),strong=strongProbability(v,p),fuel=fuelSignal(),fresh=freshestStations(),sources=4+(n?1:0)+(OBS_PRESS?1:0),obsCov=clamp(v.obsN/5,0,1),conf=clamp(Math.round(48+sources*5+obsCov*18+(fresh.length>=8?5:0)),45,98),fire=sig(-3.35+1.65*strong+1.15*v.dry+.95*v.surf+.75*fuel.signal+.45*v.obs+.35*clamp((v.localG-25)/25,0,1));return{...v,p:Math.round(p*100),strong:Math.round(strong*100),fire:Math.round(fire*100),fuelMoist:fuel.value,conf,localG:Math.max(0,v.localG)}}
async function buildZone(z){let {hrrr,nbm}=await zoneGuidance(z),h=hrrr.hourly,n=nbm?.hourly||null,a=h.time.slice(0,48).map((_,i)=>score(h,n,i,z)),pk=a.reduce((x,y)=>!x||y.p>x.p?y:x,null),gpk=a.reduce((x,y)=>!x||y.localG>x.localG?y:x,null);return{...z,a,pk,gpk}}
