const fs=require('fs'),vm=require('vm'),path=require('path');
const root=path.resolve(__dirname,'..'),core=fs.readFileSync(path.join(root,'core.js'),'utf8'),model=fs.readFileSync(path.join(root,'model.js'),'utf8');
let ui=fs.readFileSync(path.join(root,'ui.js'),'utf8').replace(/renderHealth\(\);selfTests\(\);load\(\);\s*$/,'renderHealth();selfTests();globalThis.__loadPromise=load();');
const elements=new Map();function elem(id=''){return{id,textContent:'',innerHTML:'',value:'ALL',disabled:false,children:[],style:{},classList:{add(){},remove(){}},appendChild(x){this.children.push(x)},firstElementChild:{innerHTML:''}}}function get(id){if(!elements.has(id))elements.set(id,elem(id));return elements.get(id)}
const now=new Date();now.setMinutes(0,0,0);const iso=now.toISOString();function response(x){return{ok:true,status:200,json:async()=>x,text:async()=>JSON.stringify(x)}}
async function fetchMock(input){const u=String(input);
 if(u.startsWith('./calibration.json'))return response({version:'test-cal',models:{western:{event:{intercept:0,slope:1},strong:{intercept:0,slope:1}},hybrid:{event:{intercept:0,slope:1},strong:{intercept:0,slope:1}},eastern:{event:{intercept:0,slope:1},strong:{intercept:0,slope:1}}},zone_bias_mph:{}});
 if(u.startsWith('./data/known-sundowner-events.json'))return response({events:[{date:'2016-06-18',fire_associated:true},{date:'2016-02-13',fire_associated:false}]});
 if(u.includes('geojson/network.py'))return response({features:[{properties:{sid:'RHWC1',sname:'Refugio Hills RAWS',county:'Santa Barbara'},geometry:{coordinates:[-120.0753,34.5166]}},{properties:{sid:'CUVC1',sname:'Cuyama Valley RAWS',county:'Santa Barbara'},geometry:{coordinates:[-119.8803,34.9653]}}]});
 if(u.includes('json/current.py'))return response({last_ob:{'windspeed[kt]':18,'gust[kt]':25,'winddirection[deg]':u.includes('CUVC1')?5:355,'relativehumidity[%]':22,'airtemp[F]':72,'fuel moisture[%]':8,utc_valid:iso}});
 if(u.includes('api.weather.gov/stations/')&&u.includes('/observations?')){let base=u.includes('KSBA')?1012:u.includes('KBFL')?1016:u.includes('KSMX')?1015:u.includes('KIZA')?1014:u.includes('KVBG')?1015:1014.5;return response({features:[0,3,6].map(h=>({properties:{seaLevelPressure:{value:(base+h*.03)*100},timestamp:new Date(now.getTime()-h*3600000).toISOString()}}))})}
 if(u.includes('api.weather.gov/alerts/'))return response({features:[]});if(u.includes('api.weather.gov/points/'))return response({properties:{forecastGridData:'https://example.test/grid',cwa:'LOX'}});if(u==='https://example.test/grid')return response({updateTime:iso,properties:{windGust:{uom:'wmoUnit:m_s-1',values:[{value:20}]}}});
 if(u.includes('api.open-meteo.com/v1/forecast')){const q=new URL(u).searchParams,vars=(q.get('hourly')||'').split(','),times=[],hourly={};for(let i=0;i<48;i++)times.push(new Date(now.getTime()+i*3600000).toISOString().slice(0,13)+':00');hourly.time=times;let lat=+q.get('latitude'),lon=+q.get('longitude');for(const v of vars){let val=0;if(v==='temperature_2m')val=72;else if(v==='relative_humidity_2m')val=22;else if(v==='pressure_msl')val=lon<-120.4?1015:lat>35?1016:1012;else if(v==='cloud_cover_low')val=5;else if(v==='wind_speed_10m')val=20;else if(v==='wind_direction_10m')val=5;else if(v==='wind_gusts_10m')val=35;else if(v==='boundary_layer_height')val=1800;else if(v==='lifted_index')val=4;else if(v==='shortwave_radiation')val=0;else if(v==='relative_humidity_925hPa')val=25;else if(v.startsWith('wind_speed_'))val=v.includes('500')?15:34;else if(v.startsWith('wind_direction_'))val=v.includes('500')?190:5;else if(v.startsWith('temperature_'))val=60;else if(v==='vertical_velocity_850hPa')val=-.5;hourly[v]=times.map(()=>val)}return response({hourly})}
 return{ok:false,status:404,json:async()=>({}),text:async()=>''}}
const sandbox={console,Date,Math,Number,String,Array,Object,Set,Map,JSON,RegExp,URL,URLSearchParams,setTimeout,clearTimeout,AbortController,Intl,fetch:fetchMock,window:{},globalThis:null,localStorage:{getItem(){return null},setItem(){}},document:{getElementById:get,querySelectorAll(){return[]},createElement(){return elem()}}};sandbox.globalThis=sandbox;vm.createContext(sandbox);
(async()=>{vm.runInContext(core+'\n'+model+'\n'+ui,sandbox,{timeout:5000});await sandbox.__loadPromise;const checks={complete:get('status').innerHTML.includes('Live forecast complete'),zones:(get('cards').innerHTML.match(/class="card /g)||[]).length===8,cal:get('calVersion').textContent==='test-cal',events:String(get('eventCount').textContent)==='2',nonfire:String(get('nonFireCount').textContent)==='1',self:get('selfTest').textContent==='10/10',pressure:get('pressureDrivers').innerHTML.includes('SBA–KIZA')};for(const[k,v]of Object.entries(checks))if(!v)throw Error('FAIL '+k+' '+JSON.stringify({status:get('status').innerHTML,self:get('selfTest').textContent,cards:(get('cards').innerHTML.match(/class="card /g)||[]).length,pressure:get('pressureDrivers').innerHTML.slice(0,100)}));console.log('SI3 mocked E2E PASS')})().catch(e=>{console.error(e);process.exit(1)});
