const assert=require('assert');
async function getJson(url,timeoutMs=25000){const ctl=new AbortController(),timer=setTimeout(()=>ctl.abort(),timeoutMs);try{const r=await fetch(url,{signal:ctl.signal,headers:{'User-Agent':'Sundowner-Intelligence-QA/3.0'}});assert.ok(r.ok,`${r.status} ${url}`);return await r.json()}finally{clearTimeout(timer)}}
function omUrl(lat,lon,model,vars){const q=new URLSearchParams({latitude:String(lat),longitude:String(lon),hourly:vars.join(','),wind_speed_unit:'mph',temperature_unit:'fahrenheit',timezone:'America/Los_Angeles',forecast_hours:'48',models:model});return`https://api.open-meteo.com/v1/forecast?${q}`}
(async()=>{
 const fullVars=['temperature_2m','relative_humidity_2m','pressure_msl','cloud_cover_low','wind_speed_10m','wind_direction_10m','wind_gusts_10m','boundary_layer_height','lifted_index','shortwave_radiation','relative_humidity_925hPa','wind_speed_925hPa','wind_direction_925hPa','temperature_925hPa','wind_speed_850hPa','wind_direction_850hPa','temperature_850hPa','wind_speed_700hPa','wind_direction_700hPa','temperature_700hPa','wind_speed_500hPa','wind_direction_500hPa','vertical_velocity_850hPa'];
 const seamless=await getJson(omUrl(34.45,-119.63,'gfs_seamless',fullVars));assert.ok(seamless.hourly?.time?.length>=24,'GFS seamless forecast missing');assert.ok(seamless.hourly.wind_gusts_10m?.some(Number.isFinite),'GFS gusts missing');assert.ok(seamless.hourly.wind_speed_925hPa?.some(Number.isFinite),'925-hPa winds missing');assert.ok(seamless.hourly.wind_speed_850hPa?.some(Number.isFinite),'850-hPa winds missing');assert.ok(seamless.hourly.wind_speed_500hPa?.some(Number.isFinite),'500-hPa winds missing');console.log('PASS GFS seamless SI3 fields');
 const hrrr=await getJson(omUrl(34.45,-119.63,'gfs_hrrr',fullVars));assert.ok(hrrr.hourly?.time?.length>0,'HRRR source missing');assert.ok(hrrr.hourly.wind_gusts_10m?.some(Number.isFinite),'HRRR gusts missing');assert.ok(hrrr.hourly.wind_speed_925hPa?.some(Number.isFinite),'HRRR 925-hPa winds missing');assert.ok(hrrr.hourly.wind_speed_500hPa?.some(Number.isFinite),'HRRR 500-hPa winds missing');console.log('PASS explicit HRRR production request');
 const nbm=await getJson(omUrl(34.45,-119.63,'ncep_nbm_conus',['temperature_2m','relative_humidity_2m','wind_speed_10m','wind_direction_10m','wind_gusts_10m']));assert.ok(nbm.hourly?.time?.length>0&&nbm.hourly.wind_gusts_10m?.some(Number.isFinite),'NBM source missing');console.log('PASS NBM source');
 const net=await getJson('https://mesonet.agron.iastate.edu/geojson/network.py?network=CA_DCP');assert.ok(Array.isArray(net.features)&&net.features.length>100,'CA_DCP catalog missing');const ids=new Set(net.features.map(f=>String(f.properties?.sid||f.properties?.id||f.properties?.station||f.properties?.stid||''))),coreRaws=['GVTC1','RHWC1','MPWC1','SBVC1','CXPC1','SYAC1','BMFC1','TSQC1','CUVC1'];assert.ok(coreRaws.every(id=>ids.has(id)),`Core RAWS missing: ${coreRaws.filter(id=>!ids.has(id)).join(',')}`);console.log('PASS county/Cuyama RAWS catalog');
 let reporting=0;for(const id of coreRaws){const c=await getJson(`https://mesonet.agron.iastate.edu/json/current.py?station=${id}&network=CA_DCP`);if(c.last_ob&&Object.keys(c.last_ob).length)reporting++}assert.ok(reporting>=1,'No core RAWS current observations returned');console.log(`PASS RAWS current endpoints ${reporting}/${coreRaws.length}`);
 const point=await getJson('https://api.weather.gov/points/34.45,-119.63');assert.ok(point.properties?.forecastGridData,'NWS grid-data URL missing');const grid=await getJson(point.properties.forecastGridData);assert.ok(grid.properties,'NWS grid data missing');console.log('PASS NWS grid reference');
 let primaryPressure=0,localPressure=0;for(const id of ['KSBA','KBFL','KSMX','KIZA','KVBG','KLPC']){const o=await getJson(`https://api.weather.gov/stations/${id}/observations?limit=6`),features=o.features||[],has=features.some(f=>Number.isFinite(Number(f.properties?.seaLevelPressure?.value)));if(['KSBA','KBFL','KSMX'].includes(id)&&has)primaryPressure++;if(['KIZA','KVBG','KLPC'].includes(id)&&has)localPressure++}assert.ok(primaryPressure>=2,'Primary pressure-gradient observations insufficient');console.log(`PASS observed pressure network primary=${primaryPressure}/3 local=${localPressure}/3 (local network is allowed to degrade partially)`);
 const hads=await fetch('https://mesonet.agron.iastate.edu/cgi-bin/request/hads.py?stations=RHWC1&network=CA_DCP&sts=2025-07-01T00:00Z&ets=2025-07-02T00:00Z&what=txt&delim=comma',{headers:{'User-Agent':'Sundowner-Intelligence-QA/3.0'}});assert.ok(hads.ok,`HADS history ${hads.status}`);const text=await hads.text();assert.ok(text.includes('UDIRGZZ')&&text.includes('USIRGZZ'),'Historical RAWS wind fields missing');console.log('PASS historical RAWS archive');
 console.log('Live upstream integration test: PASS');
})().catch(e=>{console.error(e);process.exit(1)});
