window.DEL_PLAYA_PROPERTIES = [
  {
    "address": "6503 Del Playa Drive",
    "short": "6503",
    "lat": 34.41055,
    "lon": -119.8557,
    "locationQuality": "Approximate map position; risk is keyed to address, not marker geometry.",
    "base": 16,
    "setback": null,
    "deck": null,
    "confidence": "Low",
    "history": "No parcel-specific failure geometry loaded yet.",
    "status": "County-monitored in February 2025 due to prior failure or potential bluff-failure exposure.",
    "setbackCurrent": false,
    "deckCurrent": false
  },
  {
    "address": "6529 Del Playa Drive",
    "short": "6529",
    "lat": 34.410437,
    "lon": -119.857283,
    "locationQuality": "Approximate map position; risk is keyed to address, not marker geometry.",
    "base": 16,
    "setback": null,
    "deck": null,
    "confidence": "Low",
    "history": "No parcel-specific failure geometry loaded yet.",
    "status": "County-monitored in February 2025 due to prior failure or potential bluff-failure exposure.",
    "setbackCurrent": false,
    "deckCurrent": false
  },
  {
    "address": "6531 Del Playa Drive",
    "short": "6531",
    "lat": 34.410428,
    "lon": -119.857405,
    "locationQuality": "Approximate map position; risk is keyed to address, not marker geometry.",
    "base": 16,
    "setback": null,
    "deck": null,
    "confidence": "Low",
    "history": "No parcel-specific failure geometry loaded yet.",
    "status": "County-monitored in February 2025 due to prior failure or potential bluff-failure exposure.",
    "setbackCurrent": false,
    "deckCurrent": false
  },
  {
    "address": "6549 Del Playa Drive",
    "short": "6549",
    "lat": 34.41035,
    "lon": -119.8585,
    "locationQuality": "Approximate map position; risk is keyed to address, not marker geometry.",
    "base": 16,
    "setback": null,
    "deck": null,
    "confidence": "Low",
    "history": "No parcel-specific failure geometry loaded yet.",
    "status": "County-monitored in February 2025 due to prior failure or potential bluff-failure exposure.",
    "setbackCurrent": false,
    "deckCurrent": false
  },
  {
    "address": "6555 Del Playa Drive",
    "short": "6555",
    "lat": 34.410324,
    "lon": -119.858865,
    "locationQuality": "Approximate map position; risk is keyed to address, not marker geometry.",
    "base": 16,
    "setback": null,
    "deck": null,
    "confidence": "Low",
    "history": "No parcel-specific failure geometry loaded yet.",
    "status": "County-monitored in February 2025 due to prior failure or potential bluff-failure exposure.",
    "setbackCurrent": false,
    "deckCurrent": false
  },
  {
    "address": "6561 Del Playa Drive",
    "short": "6561",
    "lat": 34.410298,
    "lon": -119.85923,
    "locationQuality": "Approximate map position; risk is keyed to address, not marker geometry.",
    "base": 16,
    "setback": null,
    "deck": null,
    "confidence": "Low",
    "history": "No parcel-specific failure geometry loaded yet.",
    "status": "County-monitored in February 2025 due to prior failure or potential bluff-failure exposure.",
    "setbackCurrent": false,
    "deckCurrent": false
  },
  {
    "address": "6587 Del Playa Drive",
    "short": "6587",
    "lat": 34.410185,
    "lon": -119.860813,
    "locationQuality": "Approximate map position; risk is keyed to address, not marker geometry.",
    "base": 16,
    "setback": null,
    "deck": null,
    "confidence": "Low",
    "history": "No parcel-specific failure geometry loaded yet.",
    "status": "County-monitored in February 2025 due to prior failure or potential bluff-failure exposure.",
    "setbackCurrent": false,
    "deckCurrent": false
  },
  {
    "address": "6595 Del Playa Drive",
    "short": "6595",
    "lat": 34.41015,
    "lon": -119.8613,
    "locationQuality": "Approximate map position; risk is keyed to address, not marker geometry.",
    "base": 16,
    "setback": null,
    "deck": null,
    "confidence": "Low",
    "history": "No parcel-specific failure geometry loaded yet.",
    "status": "County-monitored in February 2025 due to prior failure or potential bluff-failure exposure.",
    "setbackCurrent": false,
    "deckCurrent": false
  },
  {
    "address": "6613 Del Playa Drive",
    "short": "6613",
    "lat": 34.410072,
    "lon": -119.862396,
    "locationQuality": "Approximate map position; risk is keyed to address, not marker geometry.",
    "base": 16,
    "setback": null,
    "deck": null,
    "confidence": "Low",
    "history": "No parcel-specific failure geometry loaded yet.",
    "status": "County-monitored in February 2025 due to prior failure or potential bluff-failure exposure.",
    "setbackCurrent": false,
    "deckCurrent": false
  },
  {
    "address": "6619 Del Playa Drive",
    "short": "6619",
    "lat": 34.410046,
    "lon": -119.862761,
    "locationQuality": "Approximate map position; risk is keyed to address, not marker geometry.",
    "base": 16,
    "setback": null,
    "deck": null,
    "confidence": "Low",
    "history": "No parcel-specific failure geometry loaded yet.",
    "status": "County-monitored in February 2025 due to prior failure or potential bluff-failure exposure.",
    "setbackCurrent": false,
    "deckCurrent": false
  },
  {
    "address": "6645 Del Playa Drive",
    "short": "6645",
    "lat": 34.409933,
    "lon": -119.864344,
    "locationQuality": "Approximate map position; risk is keyed to address, not marker geometry.",
    "base": 16,
    "setback": null,
    "deck": null,
    "confidence": "Low",
    "history": "No parcel-specific failure geometry loaded yet.",
    "status": "County-monitored in February 2025 due to prior failure or potential bluff-failure exposure.",
    "setbackCurrent": false,
    "deckCurrent": false
  },
  {
    "address": "6653 Del Playa Drive",
    "short": "6653",
    "lat": 34.409898,
    "lon": -119.864831,
    "locationQuality": "Approximate map position; risk is keyed to address, not marker geometry.",
    "base": 31,
    "setback": null,
    "deck": null,
    "confidence": "High",
    "history": "Major January 2017 bluff/patio collapse; evacuation and structural cutback followed.",
    "status": "County-monitored; major historical failure site.",
    "setbackCurrent": false,
    "deckCurrent": false
  },
  {
    "address": "6663 Del Playa Drive",
    "short": "6663",
    "lat": 34.409854,
    "lon": -119.865439,
    "locationQuality": "Approximate map position; risk is keyed to address, not marker geometry.",
    "base": 27,
    "setback": null,
    "deck": null,
    "confidence": "High",
    "history": "January 2017 adjacent bluff collapse undermined balcony/patio.",
    "status": "County-monitored; historical failure exposure.",
    "setbackCurrent": false,
    "deckCurrent": false
  },
  {
    "address": "6671 Del Playa Drive",
    "short": "6671",
    "lat": 34.40982,
    "lon": -119.865926,
    "locationQuality": "Approximate map position; risk is keyed to address, not marker geometry.",
    "base": 16,
    "setback": null,
    "deck": null,
    "confidence": "Low",
    "history": "No parcel-specific failure geometry loaded yet.",
    "status": "County-monitored in February 2025 due to prior failure or potential bluff-failure exposure.",
    "setbackCurrent": false,
    "deckCurrent": false
  },
  {
    "address": "6681 Del Playa Drive",
    "short": "6681",
    "lat": 34.409776,
    "lon": -119.866535,
    "locationQuality": "Approximate map position; risk is keyed to address, not marker geometry.",
    "base": 16,
    "setback": null,
    "deck": null,
    "confidence": "Low",
    "history": "No parcel-specific failure geometry loaded yet.",
    "status": "County-monitored in February 2025 due to prior failure or potential bluff-failure exposure.",
    "setbackCurrent": false,
    "deckCurrent": false
  },
  {
    "address": "6685 Del Playa Drive",
    "short": "6685",
    "lat": 34.409759,
    "lon": -119.866778,
    "locationQuality": "Approximate map position; risk is keyed to address, not marker geometry.",
    "base": 16,
    "setback": null,
    "deck": null,
    "confidence": "Low",
    "history": "No parcel-specific failure geometry loaded yet.",
    "status": "County-monitored in February 2025 due to prior failure or potential bluff-failure exposure.",
    "setbackCurrent": false,
    "deckCurrent": false
  },
  {
    "address": "6693 Del Playa Drive",
    "short": "6693",
    "lat": 34.409724,
    "lon": -119.867265,
    "locationQuality": "Approximate map position; risk is keyed to address, not marker geometry.",
    "base": 16,
    "setback": null,
    "deck": null,
    "confidence": "Low",
    "history": "No parcel-specific failure geometry loaded yet.",
    "status": "County-monitored in February 2025 due to prior failure or potential bluff-failure exposure.",
    "setbackCurrent": false,
    "deckCurrent": false
  },
  {
    "address": "6701 Del Playa Drive",
    "short": "6701",
    "lat": 34.409689,
    "lon": -119.867752,
    "locationQuality": "Approximate map position; risk is keyed to address, not marker geometry.",
    "base": 16,
    "setback": null,
    "deck": null,
    "confidence": "Low",
    "history": "No parcel-specific failure geometry loaded yet.",
    "status": "County-monitored in February 2025 due to prior failure or potential bluff-failure exposure.",
    "setbackCurrent": false,
    "deckCurrent": false
  },
  {
    "address": "6703 Del Playa Drive",
    "short": "6703",
    "lat": 34.40968,
    "lon": -119.867874,
    "locationQuality": "Approximate map position; risk is keyed to address, not marker geometry.",
    "base": 16,
    "setback": null,
    "deck": null,
    "confidence": "Low",
    "history": "No parcel-specific failure geometry loaded yet.",
    "status": "County-monitored in February 2025 due to prior failure or potential bluff-failure exposure.",
    "setbackCurrent": false,
    "deckCurrent": false
  },
  {
    "address": "6705 Del Playa Drive",
    "short": "6705",
    "lat": 34.409672,
    "lon": -119.867996,
    "locationQuality": "Approximate map position; risk is keyed to address, not marker geometry.",
    "base": 16,
    "setback": null,
    "deck": null,
    "confidence": "Low",
    "history": "No parcel-specific failure geometry loaded yet.",
    "status": "County-monitored in February 2025 due to prior failure or potential bluff-failure exposure.",
    "setbackCurrent": false,
    "deckCurrent": false
  },
  {
    "address": "6707 Del Playa Drive",
    "short": "6707",
    "lat": 34.409663,
    "lon": -119.868117,
    "locationQuality": "Approximate map position; risk is keyed to address, not marker geometry.",
    "base": 16,
    "setback": null,
    "deck": null,
    "confidence": "Low",
    "history": "No parcel-specific failure geometry loaded yet.",
    "status": "County-monitored in February 2025 due to prior failure or potential bluff-failure exposure.",
    "setbackCurrent": false,
    "deckCurrent": false
  },
  {
    "address": "6709 Del Playa Drive",
    "short": "6709",
    "lat": 34.409654,
    "lon": -119.868239,
    "locationQuality": "Approximate map position; risk is keyed to address, not marker geometry.",
    "base": 21,
    "setback": null,
    "deck": null,
    "confidence": "Medium",
    "history": "Documented 2015 bluff loss/cutback history.",
    "status": "County-monitored.",
    "setbackCurrent": false,
    "deckCurrent": false
  },
  {
    "address": "6741 Del Playa Drive",
    "short": "6741",
    "lat": 34.409515,
    "lon": -119.870187,
    "locationQuality": "Approximate map position; risk is keyed to address, not marker geometry.",
    "base": 28,
    "setback": 20,
    "deck": null,
    "confidence": "High",
    "history": "Part of February 2024 four-property evacuation cluster; reported within 20 ft of bluff immediately before the 2024 failure.",
    "status": "County-monitored; the ~20 ft figure is historical pre-failure geometry, not a current setback.",
    "setbackCurrent": false,
    "deckCurrent": false
  },
  {
    "address": "6743 Del Playa Drive",
    "short": "6743",
    "lat": 34.409507,
    "lon": -119.870309,
    "locationQuality": "Approximate map position; risk is keyed to address, not marker geometry.",
    "base": 28,
    "setback": 20,
    "deck": null,
    "confidence": "High",
    "history": "Part of February 2024 four-property evacuation cluster; reported within 20 ft of bluff immediately before the 2024 failure.",
    "status": "County-monitored; the ~20 ft figure is historical pre-failure geometry, not a current setback.",
    "setbackCurrent": false,
    "deckCurrent": false
  },
  {
    "address": "6745 Del Playa Drive",
    "short": "6745",
    "lat": 34.409498,
    "lon": -119.87043,
    "locationQuality": "Approximate map position; risk is keyed to address, not marker geometry.",
    "base": 34,
    "setback": 19,
    "deck": 0,
    "confidence": "High",
    "history": "Deck collapsed during February 2024 storm-driven bluff failure; pre-failure reporting placed the building roughly 18–19 ft from the bluff.",
    "status": "County-monitored; 18–19 ft is historical pre-failure geometry and must not be treated as the current setback.",
    "setbackCurrent": false,
    "deckCurrent": false
  },
  {
    "address": "6747 Del Playa Drive",
    "short": "6747",
    "lat": 34.409489,
    "lon": -119.870552,
    "locationQuality": "Approximate map position; risk is keyed to address, not marker geometry.",
    "base": 32,
    "setback": 19.6,
    "deck": 2,
    "confidence": "Medium",
    "history": "A 2025 approved cutback plan would leave the dwelling about 19.6 ft from the bluff and the deck about 2 ft from the bluff.",
    "status": "County-monitored; approved post-cutback geometry is loaded, but completion/current bluff position still requires verification.",
    "setbackCurrent": false,
    "deckCurrent": false
  },
  {
    "address": "6757 Del Playa Drive",
    "short": "6757",
    "lat": 34.409446,
    "lon": -119.871161,
    "locationQuality": "Approximate map position; risk is keyed to address, not marker geometry.",
    "base": 32,
    "setback": null,
    "deck": null,
    "confidence": "High",
    "history": "Flagged for demolition because of proximity to bluff; emergency action history.",
    "status": "Current structure status requires verification before operational use.",
    "setbackCurrent": false,
    "deckCurrent": false
  },
  {
    "address": "6761 Del Playa Drive",
    "short": "6761",
    "lat": 34.409428,
    "lon": -119.871404,
    "locationQuality": "Approximate map position; risk is keyed to address, not marker geometry.",
    "base": 22,
    "setback": 30,
    "deck": null,
    "confidence": "Medium",
    "history": "A 2026 approved cutback was intended to restore approximately a 30-ft building setback.",
    "status": "Approved geometry only; verify project completion and current bluff edge before operational use.",
    "setbackCurrent": false,
    "deckCurrent": false
  },
  {
    "address": "6765 Del Playa Drive",
    "short": "6765",
    "lat": 34.409411,
    "lon": -119.871648,
    "locationQuality": "Approximate map position; risk is keyed to address, not marker geometry.",
    "base": 23,
    "setback": null,
    "deck": null,
    "confidence": "Low",
    "history": "County-monitored; current parcel-specific setback and recent structural status still need authoritative verification.",
    "status": "County-monitored; current setback needs survey verification.",
    "setbackCurrent": false,
    "deckCurrent": false
  },
  {
    "address": "6767 Del Playa Drive",
    "short": "6767",
    "lat": 34.409402,
    "lon": -119.87177,
    "locationQuality": "Approximate map position; risk is keyed to address, not marker geometry.",
    "base": 20,
    "setback": null,
    "deck": null,
    "confidence": "Low",
    "history": "County-monitored; current parcel-specific setback and recent structural status still need authoritative verification.",
    "status": "County-monitored; current setback needs survey verification.",
    "setbackCurrent": false,
    "deckCurrent": false
  },
  {
    "address": "6777 Del Playa Drive",
    "short": "6777",
    "lat": 34.409359,
    "lon": -119.872378,
    "locationQuality": "Approximate map position; risk is keyed to address, not marker geometry.",
    "base": 16,
    "setback": null,
    "deck": null,
    "confidence": "Low",
    "history": "No parcel-specific failure geometry loaded yet.",
    "status": "County-monitored in February 2025 due to prior failure or potential bluff-failure exposure.",
    "setbackCurrent": false,
    "deckCurrent": false
  },
  {
    "address": "6779 Del Playa Drive",
    "short": "6779",
    "lat": 34.40935,
    "lon": -119.8725,
    "locationQuality": "Approximate map position; risk is keyed to address, not marker geometry.",
    "base": 25,
    "setback": 19,
    "deck": null,
    "confidence": "Medium",
    "history": "Public reporting in 2024 placed the building at roughly 19 ft from the bluff; foundation type may materially alter vulnerability.",
    "status": "County-monitored; ~19 ft is historical 2024 geometry, not a verified 2026 setback.",
    "setbackCurrent": false,
    "deckCurrent": false
  }
];
