const fs=require('fs');
const START_TRAIN='2024-03-01',END_TRAIN='2024-05-31',START_TEST='2025-03-01',END_TEST='2025-05-31';
const LEADS=[1,2];
const PAIRS=[
 {name:'Gaviota',station:'GVTC1',lat:34.48,lon:-120.23,regime:'western',targetDir:345},
 {name:'Refugio',station:'RHWC1',lat:34.49,lon:-120.07,regime:'western',targetDir:355},
 {name:'San Marcos Pass',station:'MPWC1',lat:34.51,lon:-119.80,regime:'hybrid',targetDir:10},
 {name:'Montecito',station:'MTIC1',lat:34.45,lon:-119.63,regime:'eastern',targetDir:20},
 {name:'Carpinteria',station:'CXPC1',lat:34.42,lon:-119.52,regime:'eastern',targetDir:25}
];
const VARS=['relative_humidity_2m','wind_direction_10m','wind_gusts_10m','shortwave_radiation'];
const AIRPORTS={sba:[34.4262,-119.8404],bfl:[35.4336,-119.0568],smx:[34.8993,-120.4576]};
const clamp=(x,a,b)=>Math.max(a,Math.min(b,x)),sig=x=>1/(1+Math.exp(-x)),logit=p=>Math.log(clamp(p,1e-5,1-1e-5)/(1-clamp(p,1e-5,1-1e-5))),rad=x=>x*Math.PI/180;
const dirComponent=(dir,target)=>Math.max(0,Math.cos(rad((((Number(dir)-target)+540)%360)-180)));
async function getText(url,attempts=3){let last;for(let i=0;i<attempts;i++){const ctl=new AbortController(),tm=setTimeout(()=>ctl.abort(),30000);try{const r=await fetch(url,{signal:ctl.signal,headers:{'User-Agent':'Sundowner-Calibration/2.0'}});clearTimeout(tm);if(!r.ok)throw Error(`${r.status} ${await r.text()}`);return await r.text()}catch(e){clearTimeout(tm);last=e;if(i+1<attempts)await new Promise(r=>setTimeout(r,800*(i+1)))}}throw last}
async function getJson(u){return JSON.parse(await getText(u))}
function csv(s){const ls=s.trim().split(/\r?\n/),h=(ls[0]||'').split(',');return ls.slice(1).map(line=>{const a=line.split(','),o={};h.forEach((k,i)=>o[k]=a[i]??'');return o})}
async function obs(station,start,end){const u=new URL('https://mesonet.agron.iastate.edu/cgi-bin/request/hads.py');u.search=new URLSearchParams({stations:station,network:'CA_DCP',sts:`${start}T00:00Z`,ets:`${end}T23:59Z`,what:'txt',delim:'comma'});const m=new Map();for(const r of csv(await getText(u))){const speed=Number(r.USIRGZZ),gust=Number(r.UPHRGZZ),dir=Number(r.UDIRGZZ);if(!r.utc_valid||!Number.isFinite(speed)||!Number.isFinite(dir))continue;m.set(new Date(r.utc_valid.replace(' ','T')+'Z').toISOString().slice(0,13),{speed,gust:Number.isFinite(gust)?gust:null,dir})}return m}
async function one(lat,lon,v,lead,model,start,end){const u=new URL('https://previous-runs-api.open-meteo.com/v1/forecast');u.search=new URLSearchParams({latitude:String(lat),longitude:String(lon),start_date:start,end_date:end,hourly:`${v}_previous_day${lead}`,wind_speed_unit:'mph',timezone:'GMT',models:model});return getJson(u)}
async function fields(lat,lon,vars,lead,model,start,end){const h={time:null};for(const v of vars){const j=await one(lat,lon,v,lead,model,start,end);if(!h.time)h.time=j.hourly?.time||[];h[`${v}_previous_day${lead}`]=j.hourly?.[`${v}_previous_day${lead}`]||[]}return h}
const vals=(h,v,l)=>h[`${v}_previous_day${l}`]||[],idx=h=>new Map((h.time||[]).map((t,i)=>[t.slice(0,13),i]));
function raw(v,z){const press=z.regime==='western'?sig((-v.s-1.8)/.8):z.regime==='eastern'?sig((-v.b-1.2)/1):Math.max(sig((-v.s-1.8)/.8),sig((-v.b-1.2)/1)),surf=clamp((v.g*dirComponent(v.d,z.targetDir)-12)/34,0,1),dry=clamp((36-v.rh)/29,0,1),hour=Number(v.time.slice(11,13)),eve=(hour>=16||hour<=5)?1:0,tw=eve?1:clamp((350-v.sol)/350,0,1),p=sig(-4.05+1.9*press+.72*surf+.52*dry+.52*tw+.28*eve),wg=sig((-v.s-3.4)/.45),eg=sig((-v.b-4.2)/.55),grad=z.regime==='western'?wg:z.regime==='eastern'?eg:Math.max(wg,eg),sp=sig(-4.25+1.75*grad+1.55*sig((v.g-35)/3.8)+.35*clamp((p-.12)/.72,0,1));return{p,sp}}
async function rowsFor(period,lead){const [start,end]=period,model=lead===1?'gfs_hrrr':'gfs_seamless',ap={};for(const [k,[la,lo]] of Object.entries(AIRPORTS))ap[k]=await fields(la,lo,['pressure_msl'],lead,model,start,end);const ai={};for(const [k,h] of Object.entries(ap))ai[k]=idx(h);const out=[];for(const z of PAIRS){const [o,m]=await Promise.all([obs(z.station,start,end),fields(z.lat,z.lon,VARS,lead,model,start,end)]),mi=idx(m);for(const [t,x] of o){const i=mi.get(t),si=ai.sba.get(t),bi=ai.bfl.get(t),xi=ai.smx.get(t);if(i==null||si==null||bi==null||xi==null)continue;const v={time:t,b:Number(vals(ap.sba,'pressure_msl',lead)[si])-Number(vals(ap.bfl,'pressure_msl',lead)[bi]),s:Number(vals(ap.sba,'pressure_msl',lead)[si])-Number(vals(ap.smx,'pressure_msl',lead)[xi]),rh:Number(vals(m,'relative_humidity_2m',lead)[i]),g:Number(vals(m,'wind_gusts_10m',lead)[i]),d:Number(vals(m,'wind_direction_10m',lead)[i]),sol:Number(vals(m,'shortwave_radiation',lead)[i])};if(![v.b,v.s,v.rh,v.g,v.d,v.sol].every(Number.isFinite))continue;const r=raw(v,z),comp=x.speed*dirComponent(x.dir,z.targetDir);out.push({zone:z.name,regime:z.regime,p:r.p,sp:r.sp,y:comp>=20,sy:Math.max(x.gust||0,x.speed)>=35&&dirComponent(x.dir,z.targetDir)>.5})}}return out}
function fit(rows,key,label){if(!rows.length)return{a:0,b:1};let a=0,b=1;for(let it=0;it<30;it++){let g0=0,g1=0,h00=.001,h01=0,h11=.001;for(const r of rows){const x=logit(r[key]),y=r[label]?1:0,p=sig(a+b*x),w=Math.max(1e-6,p*(1-p));g0+=p-y;g1+=(p-y)*x;h00+=w;h01+=w*x;h11+=w*x*x}const det=h00*h11-h01*h01;if(Math.abs(det)<1e-9)break;const da=(h11*g0-h01*g1)/det,db=(-h01*g0+h00*g1)/det;a-=da;b-=db;if(Math.abs(da)+Math.abs(db)<1e-7)break}return{a,b}}
function apply(r,key,c){return sig(c.a+c.b*logit(r[key]))}
function auc(rows,pkey,label){const a=[...rows].sort((x,y)=>y[pkey]-x[pkey]),pos=a.filter(r=>r[label]).length,neg=a.length-pos;if(!pos||!neg)return null;let tp=0,rank=0;for(const r of a){if(r[label])tp++;else rank+=tp}return rank/(pos*neg)}
function brier(rows,pkey,label){return rows.reduce((s,r)=>s+(r[pkey]-(r[label]?1:0))**2,0)/(rows.length||1)}
function bestThreshold(rows,pkey,label){let best={t:.5,j:-99,pod:0,far:1};for(let t=.01;t<.8;t+=.01){let TP=0,FN=0,FP=0,TN=0;for(const r of rows){const pred=r[pkey]>=t,y=r[label];if(pred&&y)TP++;else if(!pred&&y)FN++;else if(pred&&!y)FP++;else TN++}const pod=TP/(TP+FN||1),fpr=FP/(FP+TN||1),far=FP/(TP+FP||1),j=pod-fpr;if(j>best.j)best={t:Number(t.toFixed(2)),j,pod,far}}return best}
function evalAt(rows,pkey,label,t){let TP=0,FN=0,FP=0,TN=0;for(const r of rows){const pred=r[pkey]>=t,y=r[label];if(pred&&y)TP++;else if(!pred&&y)FN++;else if(pred&&!y)FP++;else TN++}return{n:rows.length,events:TP+FN,pod:TP/(TP+FN||1),far:FP/(TP+FP||1),specificity:TN/(TN+FP||1)}}
(async()=>{const result={train:[START_TRAIN,END_TRAIN],test:[START_TEST,END_TEST],leads:{}};for(const lead of LEADS){console.log('LOAD',lead);const tr=await rowsFor([START_TRAIN,END_TRAIN],lead),te=await rowsFor([START_TEST,END_TEST],lead);result.leads[`${lead*24}h`]={};for(const regime of ['western','hybrid','eastern']){let a=tr.filter(r=>r.regime===regime),b=te.filter(r=>r.regime===regime);for(const [key,label,name] of [['p','y','event'],['sp','sy','strong']]){if(a.filter(r=>r[label]).length<20)a=tr;if(b.filter(r=>r[label]).length<1)b=te;const c=fit(a,key,label);for(const r of a)r[`c_${key}`]=apply(r,key,c);for(const r of b)r[`c_${key}`]=apply(r,key,c);const th=bestThreshold(a,`c_${key}`,label),ev=evalAt(b,`c_${key}`,label,th.t);result.leads[`${lead*24}h`][regime]??={};result.leads[`${lead*24}h`][regime][name]={calibration:c,threshold:th.t,train:{n:a.length,events:a.filter(r=>r[label]).length,brierRaw:brier(a,key,label),brierCal:brier(a,`c_${key}`,label)},test:{...ev,aucRaw:auc(b,key,label),aucCal:auc(b,`c_${key}`,label),brierRaw:brier(b,key,label),brierCal:brier(b,`c_${key}`,label)}};console.log(lead*24,regime,name,result.leads[`${lead*24}h`][regime][name])}}}fs.mkdirSync('validation',{recursive:true});fs.writeFileSync('validation/calibration-study.json',JSON.stringify(result,null,2)+'\n');console.log('CALIBRATION_JSON='+JSON.stringify(result));})().catch(e=>{console.error(e);process.exit(1)});
