const fs=require('fs');
const zones=[['Gaviota',34.48,-120.23,345],['Refugio',34.49,-120.07,355],['Goleta',34.45,-119.83,5],['San Marcos Pass',34.51,-119.80,10],['Mission Canyon',34.47,-119.71,15],['Montecito',34.45,-119.63,20],['Toro Canyon',34.44,-119.57,20],['Carpinteria',34.42,-119.52,25]];
const points=[...zones.map(z=>({name:z[0],lat:z[1],lon:z[2],dir:z[3],kind:'zone'})),{name:'Cuyama',lat:34.9333,lon:-119.6167,dir:0,kind:'upstream'},{name:'SBA',lat:34.4262,lon:-119.8404,kind:'pressure'},{name:'BFL',lat:35.4336,lon:-119.0568,kind:'pressure'},{name:'SMX',lat:34.8993,lon:-120.4576,kind:'pressure'}];
const vars=['temperature_2m','relative_humidity_2m','pressure_msl','wind_speed_10m','wind_direction_10m','wind_gusts_10m','wind_speed_850hPa','wind_direction_850hPa','wind_speed_700hPa','wind_direction_700hPa'];
const rad=x=>x*Math.PI/180,dc=(d,t)=>Math.max(0,Math.cos(rad((((Number(d)-t)+540)%360)-180)));
function nextDate(s){let d=new Date(s+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+1);return d.toISOString().slice(0,10)}
async function get(url,attempts=3){let last;for(let i=0;i<attempts;i++){const c=new AbortController(),tm=setTimeout(()=>c.abort(),45000);try{const r=await fetch(url,{signal:c.signal,headers:{'User-Agent':'Sundowner-Intelligence-Historical-Reconstruction/3.0'}});clearTimeout(tm);if(!r.ok)throw Error(`${r.status} ${(await r.text()).slice(0,180)}`);return await r.json()}catch(e){clearTimeout(tm);last=e;if(i+1<attempts)await new Promise(r=>setTimeout(r,1000*(i+1)))}}throw last}
function windowIndexes(h,date){const a=[];for(let i=0;i<(h.time||[]).length;i++){let t=h.time[i],day=t.slice(0,10),hour=Number(t.slice(11,13));if((day===date&&hour>=12)||(day===nextDate(date)&&hour<=8))a.push(i)}return a}
function minAt(h,k,ii){let a=ii.map(i=>Number(h[k]?.[i])).filter(Number.isFinite);return a.length?Math.min(...a):null}function maxAt(h,k,ii){let a=ii.map(i=>Number(h[k]?.[i])).filter(Number.isFinite);return a.length?Math.max(...a):null}
function maxComponent(h,speed,dir,target,ii){let best=0;for(const i of ii){let w=Number(h[speed]?.[i]),d=Number(h[dir]?.[i]);if(Number.isFinite(w)&&Number.isFinite(d))best=Math.max(best,w*dc(d,target))}return best||null}
async function reconstruct(e){const q=new URLSearchParams({latitude:points.map(p=>p.lat).join(','),longitude:points.map(p=>p.lon).join(','),start_date:e.date,end_date:nextDate(e.date),hourly:vars.join(','),wind_speed_unit:'mph',temperature_unit:'fahrenheit',timezone:'America/Los_Angeles',models:'era5'}),raw=await get('https://archive-api.open-meteo.com/v1/archive?'+q),arr=Array.isArray(raw)?raw:[raw],by={};points.forEach((p,i)=>by[p.name]=arr[i]?.hourly||{});const zoneSummary={};for(const z of zones){const h=by[z[0]],ii=windowIndexes(h,e.date),surface=maxComponent(h,'wind_speed_10m','wind_direction_10m',z[3],ii),a850=maxComponent(h,'wind_speed_850hPa','wind_direction_850hPa',z[3],ii),a700=maxComponent(h,'wind_speed_700hPa','wind_direction_700hPa',z[3],ii);zoneSummary[z[0]]={max_terrain_relative_surface_mph:surface,max_gust_mph:maxAt(h,'wind_gusts_10m',ii),min_rh_percent:minAt(h,'relative_humidity_2m',ii),max_temp_f:maxAt(h,'temperature_2m',ii),max_850_terrain_relative_mph:a850,max_700_terrain_relative_mph:a700,reanalysis_affected:surface!=null&&surface>=15}}
 const sba=by.SBA,bfl=by.BFL,smx=by.SMX,ii=windowIndexes(sba,e.date),grad=(other)=>{let vals=[];for(const i of ii){let a=Number(sba.pressure_msl?.[i]),b=Number(other.pressure_msl?.[i]);if(Number.isFinite(a)&&Number.isFinite(b))vals.push(a-b)}return vals.length?{min_mb:Math.min(...vals),max_mb:Math.max(...vals)}:null},cu=by.Cuyama,ci=windowIndexes(cu,e.date);return{event_id:e.event_id||null,date:e.date,end_date:e.end_date||null,tier:e.tier,regime:e.regime||null,fire_associated:e.fire_associated,fire_name:e.fire_name||null,documented_source:e.source||e.documented_source||null,reanalysis_source:'ERA5 via Open-Meteo Historical Weather API',analysis_window_local:`${e.date} 12:00 through ${nextDate(e.date)} 08:00`,pressure:{sba_minus_bfl:grad(bfl),sba_minus_smx:grad(smx)},upstream_cuyama:{max_northerly_component_mph:maxComponent(cu,'wind_speed_10m','wind_direction_10m',0,ci),min_rh_percent:minAt(cu,'relative_humidity_2m',ci),max_gust_mph:maxAt(cu,'wind_gusts_10m',ci)},zones:zoneSummary,documented_outcomes:{temperature_ramp_c:e.temperature_ramp_c??null,si_cdf_percent:e.si_cdf_percent??null,max_sustained_mph:e.max_sustained_mph??null,max_gust_mph:e.max_gust_mph??null,onset_local:e.onset_local??null,end_local:e.end_local??null}}}
(async()=>{const cat=JSON.parse(fs.readFileSync('data/known-sundowner-events.json','utf8')),swex=fs.existsSync('data/swex-2022-events.json')?JSON.parse(fs.readFileSync('data/swex-2022-events.json','utf8')):{events:[]},events=[...(cat.events||[]),...(swex.events||[]).map(e=>({...e,source:e.source||'witte2026_swex'}))],out=[];for(let i=0;i<events.length;i++){process.stdout.write(`reconstruct ${i+1}/${events.length} ${events[i].event_id||events[i].date}\n`);try{out.push(await reconstruct(events[i]))}catch(e){out.push({event_id:events[i].event_id||null,date:events[i].date,tier:events[i].tier,fire_associated:events[i].fire_associated,error:String(e.message||e)})}await new Promise(r=>setTimeout(r,200))}const ok=out.filter(x=>!x.error).length,result={version:'SI-3.0-historical-reconstruction',generated:new Date().toISOString(),method:'Documented Sundowner truth sets joined to ERA5 hourly reanalysis for a standard afternoon-to-morning event window. Includes peer-reviewed/historical cases plus the complete 2022 SWEX IOP set. Reanalysis features support analog/context analysis; documented station outcomes remain preferred and fire association is never a meteorological predictor.',events_total:events.length,reconstructed:ok,failed:out.length-ok,events:out};fs.writeFileSync('data/historical-event-reconstructions.json',JSON.stringify(result,null,2)+'\n');if(!ok)throw Error('No historical events reconstructed');console.log(`reconstructed ${ok}/${out.length}`)})().catch(e=>{console.error(e);process.exit(1)});
